content = (
    "import pandas as pd\n"
    "import sqlite3\n"
    "import os\n"
    "import sys\n"
    "from pathlib import Path\n\n"
    "sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))\n"
    "from config.settings import get_config, get_logger\n\n"
    "logger = get_logger('loader')\n"
    "cfg    = get_config()\n\n"
    "DB_PATH = Path(cfg['paths']['raw_data_lake']).parent / 'ecommerce_dw.db'\n\n"
    "def get_conn():\n"
    "    DB_PATH.parent.mkdir(parents=True, exist_ok=True)\n"
    "    return sqlite3.connect(DB_PATH)\n\n"
    "def create_tables(conn):\n"
    "    conn.executescript('''\n"
    "        CREATE TABLE IF NOT EXISTS dim_category (\n"
    "            category_slug TEXT PRIMARY KEY,\n"
    "            category_name TEXT NOT NULL\n"
    "        );\n"
    "        CREATE TABLE IF NOT EXISTS dim_seller (\n"
    "            seller_name TEXT PRIMARY KEY\n"
    "        );\n"
    "        CREATE TABLE IF NOT EXISTS dim_product (\n"
    "            product_id INTEGER PRIMARY KEY,\n"
    "            title TEXT,\n"
    "            currency TEXT,\n"
    "            has_variations INTEGER\n"
    "        );\n"
    "        CREATE TABLE IF NOT EXISTS fact_product_listing (\n"
    "            id INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "            product_id INTEGER,\n"
    "            category_slug TEXT,\n"
    "            seller_name TEXT,\n"
    "            initial_price REAL,\n"
    "            final_price REAL,\n"
    "            discount REAL,\n"
    "            discount_amount REAL,\n"
    "            is_discounted INTEGER,\n"
    "            price_bucket TEXT,\n"
    "            rating REAL,\n"
    "            ratings_count INTEGER,\n"
    "            ratings_tier TEXT,\n"
    "            rating_x_count REAL,\n"
    "            title_word_count INTEGER,\n"
    "            has_seller INTEGER\n"
    "        );\n"
    "    ''')\n"
    "    conn.commit()\n"
    "    logger.info('Tables created OK')\n\n"
    "def load_dim_category(df, conn):\n"
    "    cats = df[['category_slug','category']].drop_duplicates(subset=['category_slug'])\n"
    "    cats.columns = ['category_slug','category_name']\n"
    "    cats.to_sql('dim_category', conn, if_exists='replace', index=False)\n"
    "    logger.info('dim_category: %d rows', len(cats))\n\n"
    "def load_dim_seller(df, conn):\n"
    "    sellers = df[['seller_name']].drop_duplicates()\n"
    "    sellers.to_sql('dim_seller', conn, if_exists='replace', index=False)\n"
    "    logger.info('dim_seller: %d rows', len(sellers))\n\n"
    "def load_dim_product(df, conn):\n"
    "    prods = df[['product_id','title','currency','has_variations']].drop_duplicates(subset=['product_id'])\n"
    "    prods.to_sql('dim_product', conn, if_exists='replace', index=False)\n"
    "    logger.info('dim_product: %d rows', len(prods))\n\n"
    "def load_fact(df, conn):\n"
    "    cols = ['product_id','category_slug','seller_name','initial_price','final_price',\n"
    "            'discount','discount_amount','is_discounted','price_bucket','rating',\n"
    "            'ratings_count','ratings_tier','rating_x_count','title_word_count','has_seller']\n"
    "    df[cols].to_sql('fact_product_listing', conn, if_exists='replace', index=False)\n"
    "    logger.info('fact_product_listing: %d rows', len(df))\n\n"
    "def run_load():\n"
    "    proc_file = Path(cfg['paths']['processed_data']) / 'products_cleaned.parquet'\n"
    "    if not proc_file.exists():\n"
    "        raise FileNotFoundError(f'Not found: {proc_file}')\n"
    "    df = pd.read_parquet(proc_file)\n"
    "    logger.info('Loaded %d rows', len(df))\n"
    "    conn = get_conn()\n"
    "    create_tables(conn)\n"
    "    load_dim_category(df, conn)\n"
    "    load_dim_seller(df, conn)\n"
    "    load_dim_product(df, conn)\n"
    "    load_fact(df, conn)\n"
    "    conn.close()\n"
    "    logger.info('Load complete')\n"
    "    print('Done! Database saved at:', DB_PATH)\n\n"
    "if __name__ == '__main__':\n"
    "    run_load()\n"
)

with open('warehouse/loader.py', 'w', encoding='utf-8') as f:
    f.write(content)

print('loader.py created OK')